/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mod_utilisateur (void)
{
  GtkWidget *mod_utilisateur;
  GtkWidget *fixed2;
  GtkWidget *mod3;
  GtkWidget *mod4;
  GtkWidget *mod1;
  GtkWidget *mod5;
  GtkWidget *mod2;
  GtkWidget *label22;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label1;
  GtkWidget *label3;
  GtkWidget *mod6;
  GtkWidget *label4;
  GtkWidget *label45;
  GtkWidget *check_id;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *button_mod;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label5;
  GtkWidget *button1;
  GtkWidget *alignment15;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label49;

  mod_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mod_utilisateur, 800, 765);
  gtk_window_set_title (GTK_WINDOW (mod_utilisateur), _("Modifier un utilisateur"));
  gtk_window_set_position (GTK_WINDOW (mod_utilisateur), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (mod_utilisateur), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (mod_utilisateur), fixed2);

  mod3 = gtk_entry_new ();
  gtk_widget_show (mod3);
  gtk_fixed_put (GTK_FIXED (fixed2), mod3, 190, 320);
  gtk_widget_set_size_request (mod3, 180, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod3), 8226);

  mod4 = gtk_entry_new ();
  gtk_widget_show (mod4);
  gtk_fixed_put (GTK_FIXED (fixed2), mod4, 190, 395);
  gtk_widget_set_size_request (mod4, 180, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod4), 8226);

  mod1 = gtk_entry_new ();
  gtk_widget_show (mod1);
  gtk_fixed_put (GTK_FIXED (fixed2), mod1, 304, 144);
  gtk_widget_set_size_request (mod1, 180, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod1), 8226);

  mod5 = gtk_entry_new ();
  gtk_widget_show (mod5);
  gtk_fixed_put (GTK_FIXED (fixed2), mod5, 190, 470);
  gtk_widget_set_size_request (mod5, 180, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod5), 8226);

  mod2 = gtk_combo_box_new_text ();
  gtk_widget_show (mod2);
  gtk_fixed_put (GTK_FIXED (fixed2), mod2, 190, 245);
  gtk_widget_set_size_request (mod2, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod2), _("Administrateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod2), _("Technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod2), _("Responsable r\303\251clamations"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod2), _("Agent de foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod2), _("Agent de restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod2), _("Etudiant"));

  label22 = gtk_label_new (_("<span foreground=\"red\">Role :</span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 95, 250);
  gtk_widget_set_size_request (label22, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label7 = gtk_label_new (_("<span foreground=\"red\">Pr\303\251nom :</span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 95, 325);
  gtk_widget_set_size_request (label7, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label8 = gtk_label_new (_("<span foreground=\"red\">Nom :</span>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 95, 400);
  gtk_widget_set_size_request (label8, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label1 = gtk_label_new (_("<span foreground=\"red\">Email :</span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 95, 475);
  gtk_widget_set_size_request (label1, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  label3 = gtk_label_new (_("<span foreground=\"red\">Niveau :</span>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 90, 550);
  gtk_widget_set_size_request (label3, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  mod6 = gtk_combo_box_new_text ();
  gtk_widget_show (mod6);
  gtk_fixed_put (GTK_FIXED (fixed2), mod6, 190, 545);
  gtk_widget_set_size_request (mod6, 180, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod6), _("1\303\250re ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod6), _("2\303\251me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod6), _("3\303\251me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod6), _("4\303\251me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod6), _("5\303\251me ann\303\251e"));

  label4 = gtk_label_new (_("<span foreground=\"red\">ID :</span>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 248, 152);
  gtk_widget_set_size_request (label4, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  label45 = gtk_label_new (_("<span foreground=\"blue\"><b>Modifier votre utilisateur</b></span>"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed2), label45, 288, 24);
  gtk_widget_set_size_request (label45, 232, 41);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  check_id = gtk_button_new ();
  gtk_widget_show (check_id);
  gtk_fixed_put (GTK_FIXED (fixed2), check_id, 528, 136);
  gtk_widget_set_size_request (check_id, 104, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (check_id), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("V\303\251rifier"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed2), button_mod, 230, 620);
  gtk_widget_set_size_request (button_mod, 120, 50);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed2), button1, 460, 620);
  gtk_widget_set_size_request (button1, 120, 50);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button1), alignment15);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox13), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) check_id, "clicked",
                    G_CALLBACK (on_check_id_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod_utilisateur, mod_utilisateur, "mod_utilisateur");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, mod3, "mod3");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, mod4, "mod4");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, mod1, "mod1");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, mod5, "mod5");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, mod2, "mod2");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label22, "label22");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label7, "label7");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label8, "label8");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label1, "label1");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label3, "label3");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, mod6, "mod6");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label4, "label4");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label45, "label45");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, check_id, "check_id");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, image2, "image2");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label6, "label6");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, image1, "image1");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label5, "label5");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, button1, "button1");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, image13, "image13");
  GLADE_HOOKUP_OBJECT (mod_utilisateur, label49, "label49");

  return mod_utilisateur;
}

GtkWidget*
create_af_utilisateur (void)
{
  GtkWidget *af_utilisateur;
  GtkWidget *fixed3;
  GtkWidget *image16;
  GtkWidget *image17;
  GtkWidget *scrolledwindow1;
  GtkWidget *alignment4;
  GtkWidget *treeview_utilisateur;
  GtkWidget *modifier;
  GtkWidget *alignment11;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label42;
  GtkWidget *rechercher;
  GtkWidget *alignment12;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label43;
  GtkWidget *reclam;
  GtkWidget *alignment13;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label44;
  GtkWidget *button_af;
  GtkWidget *alignment5;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *ajouter;
  GtkWidget *alignment8;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label39;
  GtkWidget *label10;

  af_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (af_utilisateur, 800, 765);
  gtk_window_set_title (GTK_WINDOW (af_utilisateur), _("Liste des utilisateurs"));
  gtk_window_set_position (GTK_WINDOW (af_utilisateur), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (af_utilisateur), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (af_utilisateur), fixed3);

  image16 = create_pixmap (af_utilisateur, "gh.jpg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed3), image16, 0, 0);
  gtk_widget_set_size_request (image16, 800, 765);

  image17 = create_pixmap (af_utilisateur, "index.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed3), image17, 0, 48);
  gtk_widget_set_size_request (image17, 800, 30);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 25, 130);
  gtk_widget_set_size_request (scrolledwindow1, 750, 370);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), alignment4);

  treeview_utilisateur = gtk_tree_view_new ();
  gtk_widget_show (treeview_utilisateur);
  gtk_container_add (GTK_CONTAINER (alignment4), treeview_utilisateur);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview_utilisateur), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview_utilisateur), TRUE);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier, 600, 530);
  gtk_widget_set_size_request (modifier, 110, 50);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (modifier), alignment11);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox9), label42, FALSE, FALSE, 0);

  rechercher = gtk_button_new ();
  gtk_widget_show (rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), rechercher, 600, 600);
  gtk_widget_set_size_request (rechercher, 110, 50);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (rechercher), alignment12);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox10), label43, FALSE, FALSE, 0);

  reclam = gtk_button_new ();
  gtk_widget_show (reclam);
  gtk_fixed_put (GTK_FIXED (fixed3), reclam, 250, 558);
  gtk_widget_set_size_request (reclam, 310, 65);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (reclam), alignment13);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Service le plus r\303\251clam\303\251"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox11), label44, FALSE, FALSE, 0);

  button_af = gtk_button_new ();
  gtk_widget_show (button_af);
  gtk_fixed_put (GTK_FIXED (fixed3), button_af, 100, 530);
  gtk_widget_set_size_request (button_af, 110, 50);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_af), alignment5);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter, 100, 600);
  gtk_widget_set_size_request (ajouter, 110, 50);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment8);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox6), label39, FALSE, FALSE, 0);

  label10 = gtk_label_new (_("<span foreground=\"blue\"><b>Liste des utilisateurs</b></span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 250, 34);
  gtk_widget_set_size_request (label10, 300, 60);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  g_signal_connect ((gpointer) treeview_utilisateur, "row_activated",
                    G_CALLBACK (on_treeview_utilisateur_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher, "clicked",
                    G_CALLBACK (on_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) reclam, "clicked",
                    G_CALLBACK (on_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_af, "clicked",
                    G_CALLBACK (on_button_af_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (af_utilisateur, af_utilisateur, "af_utilisateur");
  GLADE_HOOKUP_OBJECT (af_utilisateur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image16, "image16");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image17, "image17");
  GLADE_HOOKUP_OBJECT (af_utilisateur, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (af_utilisateur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (af_utilisateur, treeview_utilisateur, "treeview_utilisateur");
  GLADE_HOOKUP_OBJECT (af_utilisateur, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (af_utilisateur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (af_utilisateur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image9, "image9");
  GLADE_HOOKUP_OBJECT (af_utilisateur, label42, "label42");
  GLADE_HOOKUP_OBJECT (af_utilisateur, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (af_utilisateur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (af_utilisateur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image10, "image10");
  GLADE_HOOKUP_OBJECT (af_utilisateur, label43, "label43");
  GLADE_HOOKUP_OBJECT (af_utilisateur, reclam, "reclam");
  GLADE_HOOKUP_OBJECT (af_utilisateur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (af_utilisateur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image11, "image11");
  GLADE_HOOKUP_OBJECT (af_utilisateur, label44, "label44");
  GLADE_HOOKUP_OBJECT (af_utilisateur, button_af, "button_af");
  GLADE_HOOKUP_OBJECT (af_utilisateur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (af_utilisateur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image3, "image3");
  GLADE_HOOKUP_OBJECT (af_utilisateur, label11, "label11");
  GLADE_HOOKUP_OBJECT (af_utilisateur, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (af_utilisateur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (af_utilisateur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (af_utilisateur, image6, "image6");
  GLADE_HOOKUP_OBJECT (af_utilisateur, label39, "label39");
  GLADE_HOOKUP_OBJECT (af_utilisateur, label10, "label10");

  return af_utilisateur;
}

GtkWidget*
create_aj_utilisateur (void)
{
  GtkWidget *aj_utilisateur;
  GtkWidget *fixed4;
  GtkWidget *aj5;
  GtkWidget *ajc;
  GtkWidget *aj3;
  GtkWidget *aj4;
  GtkObject *aj1_adj;
  GtkWidget *aj1;
  GtkWidget *aj2;
  GtkWidget *h;
  GSList *h_group = NULL;
  GtkWidget *f;
  GtkWidget *button_aj;
  GtkWidget *alignment14;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label46;
  GtkWidget *button2;
  GtkWidget *alignment16;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label50;
  GtkWidget *image18;
  GtkWidget *image19;
  GtkWidget *image20;
  GtkWidget *image21;
  GtkWidget *image22;
  GtkWidget *image23;
  GtkWidget *image24;
  GtkWidget *image25;
  GtkWidget *image26;
  GtkWidget *image28;
  GtkWidget *label13;
  GtkWidget *label20;
  GtkWidget *label14;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label16;
  GtkWidget *label19;
  GtkWidget *image27;
  GtkWidget *aj6;
  GtkWidget *label21;
  GtkWidget *label15;
  GtkWidget *label47;

  aj_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (aj_utilisateur, 800, 765);
  gtk_window_set_title (GTK_WINDOW (aj_utilisateur), _("Ajouter un utilisateur"));
  gtk_window_set_position (GTK_WINDOW (aj_utilisateur), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (aj_utilisateur), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (aj_utilisateur), fixed4);

  aj5 = gtk_entry_new ();
  gtk_widget_show (aj5);
  gtk_fixed_put (GTK_FIXED (fixed4), aj5, 200, 312);
  gtk_widget_set_size_request (aj5, 175, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj5), 8226);

  ajc = gtk_calendar_new ();
  gtk_widget_show (ajc);
  gtk_fixed_put (GTK_FIXED (fixed4), ajc, 200, 455);
  gtk_widget_set_size_request (ajc, 175, 180);
  gtk_calendar_display_options (GTK_CALENDAR (ajc),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  aj3 = gtk_entry_new ();
  gtk_widget_show (aj3);
  gtk_fixed_put (GTK_FIXED (fixed4), aj3, 200, 242);
  gtk_widget_set_size_request (aj3, 175, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj3), 8226);

  aj4 = gtk_entry_new ();
  gtk_widget_show (aj4);
  gtk_fixed_put (GTK_FIXED (fixed4), aj4, 500, 242);
  gtk_widget_set_size_request (aj4, 175, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj4), 8226);

  aj1_adj = gtk_adjustment_new (11, 0, 1000, 1, 10, 10);
  aj1 = gtk_spin_button_new (GTK_ADJUSTMENT (aj1_adj), 1, 0);
  gtk_widget_show (aj1);
  gtk_fixed_put (GTK_FIXED (fixed4), aj1, 200, 108);
  gtk_widget_set_size_request (aj1, 75, 30);

  aj2 = gtk_combo_box_new_text ();
  gtk_widget_show (aj2);
  gtk_fixed_put (GTK_FIXED (fixed4), aj2, 200, 170);
  gtk_widget_set_size_request (aj2, 175, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj2), _("Administrateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj2), _("Technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj2), _("Responsable r\303\251clamations"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj2), _("Agent de foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj2), _("Agent de restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj2), _("Etudiant"));

  h = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (h);
  gtk_fixed_put (GTK_FIXED (fixed4), h, 200, 385);
  gtk_widget_set_size_request (h, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (h), h_group);
  h_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (h));

  f = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (f);
  gtk_fixed_put (GTK_FIXED (fixed4), f, 350, 385);
  gtk_widget_set_size_request (f, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (f), h_group);
  h_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (f));

  button_aj = gtk_button_new ();
  gtk_widget_show (button_aj);
  gtk_fixed_put (GTK_FIXED (fixed4), button_aj, 250, 705);
  gtk_widget_set_size_request (button_aj, 130, 50);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_aj), alignment14);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox12), label46, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 440, 705);
  gtk_widget_set_size_request (button2, 130, 50);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button2), alignment16);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox14), label50, FALSE, FALSE, 0);

  image18 = create_pixmap (aj_utilisateur, "gh.jpg");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed4), image18, 0, 0);
  gtk_widget_set_size_request (image18, 800, 765);

  image19 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed4), image19, 100, 112);
  gtk_widget_set_size_request (image19, 70, 25);

  image20 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed4), image20, 100, 175);
  gtk_widget_set_size_request (image20, 70, 25);

  image21 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed4), image21, 100, 245);
  gtk_widget_set_size_request (image21, 70, 25);

  image22 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed4), image22, 400, 245);
  gtk_widget_set_size_request (image22, 70, 25);

  image23 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed4), image23, 100, 320);
  gtk_widget_set_size_request (image23, 70, 25);

  image24 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed4), image24, 100, 385);
  gtk_widget_set_size_request (image24, 70, 25);

  image25 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed4), image25, 32, 455);
  gtk_widget_set_size_request (image25, 140, 25);

  image26 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed4), image26, 100, 655);
  gtk_widget_set_size_request (image26, 70, 25);

  image28 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed4), image28, 270, 0);
  gtk_widget_set_size_request (image28, 268, 40);

  label13 = gtk_label_new (_("<span foreground=\"red\">ID :</span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 100, 112);
  gtk_widget_set_size_request (label13, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label20 = gtk_label_new (_("<span foreground=\"red\">Role :</span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 100, 175);
  gtk_widget_set_size_request (label20, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label14 = gtk_label_new (_("<span foreground=\"red\">Pr\303\251nom :</span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 100, 245);
  gtk_widget_set_size_request (label14, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label17 = gtk_label_new (_("<span foreground=\"red\">Email :</span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 100, 320);
  gtk_widget_set_size_request (label17, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<span foreground=\"red\">Sexe :</span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 100, 385);
  gtk_widget_set_size_request (label18, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label16 = gtk_label_new (_("<span foreground=\"red\">Date de naissance :</span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 32, 455);
  gtk_widget_set_size_request (label16, 140, 25);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label19 = gtk_label_new (_("<span foreground=\"red\">Niveau :</span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 100, 655);
  gtk_widget_set_size_request (label19, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  image27 = create_pixmap (aj_utilisateur, "index.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed4), image27, 400, 656);
  gtk_widget_set_size_request (image27, 264, 25);

  aj6 = gtk_combo_box_new_text ();
  gtk_widget_show (aj6);
  gtk_fixed_put (GTK_FIXED (fixed4), aj6, 200, 650);
  gtk_widget_set_size_request (aj6, 175, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj6), _("1\303\250re ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj6), _("2\303\251me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj6), _("3\303\251me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj6), _("4\303\251me ann\303\251e"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj6), _("5\303\251me ann\303\251e"));

  label21 = gtk_label_new (_("( Laissez vide s'il s'agit d'un employ\303\251 )"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 400, 655);
  gtk_widget_set_size_request (label21, 264, 25);

  label15 = gtk_label_new (_("<span foreground=\"red\">Nom :</span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 400, 245);
  gtk_widget_set_size_request (label15, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label47 = gtk_label_new (_("<span foreground=\"blue\"><b>Ajouter votre utilisateur</b></span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 272, 0);
  gtk_widget_set_size_request (label47, 268, 40);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  g_signal_connect ((gpointer) button_aj, "clicked",
                    G_CALLBACK (on_button_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aj_utilisateur, aj_utilisateur, "aj_utilisateur");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, aj5, "aj5");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, ajc, "ajc");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, aj3, "aj3");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, aj4, "aj4");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, aj1, "aj1");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, aj2, "aj2");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, h, "h");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, f, "f");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, button_aj, "button_aj");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image12, "image12");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label46, "label46");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, button2, "button2");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image14, "image14");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label50, "label50");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image18, "image18");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image19, "image19");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image20, "image20");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image21, "image21");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image22, "image22");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image23, "image23");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image24, "image24");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image25, "image25");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image26, "image26");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image28, "image28");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label13, "label13");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label20, "label20");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label14, "label14");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label17, "label17");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label18, "label18");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label16, "label16");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label19, "label19");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, image27, "image27");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, aj6, "aj6");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label21, "label21");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label15, "label15");
  GLADE_HOOKUP_OBJECT (aj_utilisateur, label47, "label47");

  return aj_utilisateur;
}

GtkWidget*
create_recherche (void)
{
  GtkWidget *recherche;
  GtkWidget *fixed5;
  GtkWidget *r1;
  GtkWidget *chercher;
  GtkWidget *alignment7;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label36;
  GtkWidget *button3;
  GtkWidget *alignment17;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label51;
  GtkWidget *vseparator1;
  GtkWidget *image33;
  GtkWidget *image32;
  GtkWidget *image36;
  GtkWidget *image35;
  GtkWidget *image37;
  GtkWidget *image38;
  GtkWidget *image39;
  GtkWidget *label37;
  GtkWidget *label26;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label28;
  GtkWidget *image31;
  GtkWidget *label27;
  GtkWidget *image30;
  GtkWidget *label48;
  GtkWidget *image40;
  GtkWidget *image41;
  GtkWidget *image44;
  GtkWidget *image45;
  GtkWidget *image46;
  GtkWidget *r2;
  GtkWidget *r3;
  GtkWidget *label38;
  GtkWidget *image42;
  GtkWidget *r4;
  GtkWidget *image43;
  GtkWidget *r5;
  GtkWidget *r6;
  GtkWidget *r7;
  GtkWidget *r8;

  recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (recherche, 800, 765);
  gtk_window_set_title (GTK_WINDOW (recherche), _("Chercher un utilisateur"));
  gtk_window_set_position (GTK_WINDOW (recherche), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (recherche), FALSE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (recherche), fixed5);

  r1 = gtk_entry_new ();
  gtk_widget_show (r1);
  gtk_fixed_put (GTK_FIXED (fixed5), r1, 384, 126);
  gtk_widget_set_size_request (r1, 70, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (r1), 8226);

  chercher = gtk_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher, 500, 120);
  gtk_widget_set_size_request (chercher, 110, 50);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (chercher), alignment7);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox5), label36, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed5), button3, 320, 630);
  gtk_widget_set_size_request (button3, 130, 50);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button3), alignment17);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox15), label51, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), vseparator1, 72, 560);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  image33 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed5), image33, 110, 290);
  gtk_widget_set_size_request (image33, 70, 25);

  image32 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed5), image32, 110, 240);
  gtk_widget_set_size_request (image32, 70, 25);

  image36 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed5), image36, 110, 344);
  gtk_widget_set_size_request (image36, 70, 25);

  image35 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed5), image35, 110, 390);
  gtk_widget_set_size_request (image35, 70, 25);

  image37 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed5), image37, 110, 440);
  gtk_widget_set_size_request (image37, 70, 25);

  image38 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed5), image38, 40, 490);
  gtk_widget_set_size_request (image38, 140, 25);

  image39 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed5), image39, 110, 540);
  gtk_widget_set_size_request (image39, 70, 25);

  label37 = gtk_label_new (_("<span foreground=\"red\">Pr\303\251nom :</span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 110, 290);
  gtk_widget_set_size_request (label37, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label26 = gtk_label_new (_("<span foreground=\"red\">Role :</span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 112, 240);
  gtk_widget_set_size_request (label26, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label23 = gtk_label_new (_("<span foreground=\"red\">Email :</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 114, 390);
  gtk_widget_set_size_request (label23, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<span foreground=\"red\">Sexe :</span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 114, 440);
  gtk_widget_set_size_request (label24, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<span foreground=\"red\">Niveau :</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 108, 540);
  gtk_widget_set_size_request (label25, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"red\">Date de naissance :</span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 36, 490);
  gtk_widget_set_size_request (label28, 140, 25);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  image31 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed5), image31, 296, 128);
  gtk_widget_set_size_request (image31, 70, 25);

  label27 = gtk_label_new (_("<span foreground=\"red\">ID :</span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 296, 128);
  gtk_widget_set_size_request (label27, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  image30 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed5), image30, 304, 24);
  gtk_widget_set_size_request (image30, 200, 40);

  label48 = gtk_label_new (_("<span foreground=\"blue\"><b>Chercher votre utilisateur</b></span>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed5), label48, 304, 24);
  gtk_widget_set_size_request (label48, 200, 40);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  image40 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed5), image40, 210, 240);
  gtk_widget_set_size_request (image40, 232, 32);

  image41 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed5), image41, 210, 288);
  gtk_widget_set_size_request (image41, 232, 32);

  image44 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image44);
  gtk_fixed_put (GTK_FIXED (fixed5), image44, 210, 440);
  gtk_widget_set_size_request (image44, 232, 32);

  image45 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image45);
  gtk_fixed_put (GTK_FIXED (fixed5), image45, 210, 490);
  gtk_widget_set_size_request (image45, 232, 32);

  image46 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image46);
  gtk_fixed_put (GTK_FIXED (fixed5), image46, 210, 540);
  gtk_widget_set_size_request (image46, 232, 32);

  r2 = gtk_label_new ("");
  gtk_widget_show (r2);
  gtk_fixed_put (GTK_FIXED (fixed5), r2, 208, 240);
  gtk_widget_set_size_request (r2, 232, 32);

  r3 = gtk_label_new ("");
  gtk_widget_show (r3);
  gtk_fixed_put (GTK_FIXED (fixed5), r3, 208, 288);
  gtk_widget_set_size_request (r3, 232, 32);

  label38 = gtk_label_new (_("<span foreground=\"red\">Nom :</span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 114, 344);
  gtk_widget_set_size_request (label38, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  image42 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed5), image42, 210, 340);
  gtk_widget_set_size_request (image42, 232, 32);

  r4 = gtk_label_new ("");
  gtk_widget_show (r4);
  gtk_fixed_put (GTK_FIXED (fixed5), r4, 210, 340);
  gtk_widget_set_size_request (r4, 232, 32);

  image43 = create_pixmap (recherche, "index.png");
  gtk_widget_show (image43);
  gtk_fixed_put (GTK_FIXED (fixed5), image43, 210, 390);
  gtk_widget_set_size_request (image43, 232, 32);

  r5 = gtk_label_new ("");
  gtk_widget_show (r5);
  gtk_fixed_put (GTK_FIXED (fixed5), r5, 208, 392);
  gtk_widget_set_size_request (r5, 232, 32);

  r6 = gtk_label_new ("");
  gtk_widget_show (r6);
  gtk_fixed_put (GTK_FIXED (fixed5), r6, 208, 440);
  gtk_widget_set_size_request (r6, 232, 32);

  r7 = gtk_label_new ("");
  gtk_widget_show (r7);
  gtk_fixed_put (GTK_FIXED (fixed5), r7, 208, 488);
  gtk_widget_set_size_request (r7, 232, 32);

  r8 = gtk_label_new ("");
  gtk_widget_show (r8);
  gtk_fixed_put (GTK_FIXED (fixed5), r8, 208, 536);
  gtk_widget_set_size_request (r8, 232, 32);

  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (recherche, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (recherche, r1, "r1");
  GLADE_HOOKUP_OBJECT (recherche, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (recherche, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (recherche, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (recherche, image5, "image5");
  GLADE_HOOKUP_OBJECT (recherche, label36, "label36");
  GLADE_HOOKUP_OBJECT (recherche, button3, "button3");
  GLADE_HOOKUP_OBJECT (recherche, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (recherche, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (recherche, image15, "image15");
  GLADE_HOOKUP_OBJECT (recherche, label51, "label51");
  GLADE_HOOKUP_OBJECT (recherche, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (recherche, image33, "image33");
  GLADE_HOOKUP_OBJECT (recherche, image32, "image32");
  GLADE_HOOKUP_OBJECT (recherche, image36, "image36");
  GLADE_HOOKUP_OBJECT (recherche, image35, "image35");
  GLADE_HOOKUP_OBJECT (recherche, image37, "image37");
  GLADE_HOOKUP_OBJECT (recherche, image38, "image38");
  GLADE_HOOKUP_OBJECT (recherche, image39, "image39");
  GLADE_HOOKUP_OBJECT (recherche, label37, "label37");
  GLADE_HOOKUP_OBJECT (recherche, label26, "label26");
  GLADE_HOOKUP_OBJECT (recherche, label23, "label23");
  GLADE_HOOKUP_OBJECT (recherche, label24, "label24");
  GLADE_HOOKUP_OBJECT (recherche, label25, "label25");
  GLADE_HOOKUP_OBJECT (recherche, label28, "label28");
  GLADE_HOOKUP_OBJECT (recherche, image31, "image31");
  GLADE_HOOKUP_OBJECT (recherche, label27, "label27");
  GLADE_HOOKUP_OBJECT (recherche, image30, "image30");
  GLADE_HOOKUP_OBJECT (recherche, label48, "label48");
  GLADE_HOOKUP_OBJECT (recherche, image40, "image40");
  GLADE_HOOKUP_OBJECT (recherche, image41, "image41");
  GLADE_HOOKUP_OBJECT (recherche, image44, "image44");
  GLADE_HOOKUP_OBJECT (recherche, image45, "image45");
  GLADE_HOOKUP_OBJECT (recherche, image46, "image46");
  GLADE_HOOKUP_OBJECT (recherche, r2, "r2");
  GLADE_HOOKUP_OBJECT (recherche, r3, "r3");
  GLADE_HOOKUP_OBJECT (recherche, label38, "label38");
  GLADE_HOOKUP_OBJECT (recherche, image42, "image42");
  GLADE_HOOKUP_OBJECT (recherche, r4, "r4");
  GLADE_HOOKUP_OBJECT (recherche, image43, "image43");
  GLADE_HOOKUP_OBJECT (recherche, r5, "r5");
  GLADE_HOOKUP_OBJECT (recherche, r6, "r6");
  GLADE_HOOKUP_OBJECT (recherche, r7, "r7");
  GLADE_HOOKUP_OBJECT (recherche, r8, "r8");

  return recherche;
}

